name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      env:
        TOKEN: ${{ secrets.TOKEN }}
        SELENIUM_HUB_HOST: 'http://localhost:4444/wd/hub'
        GITHUB_RUN: True
      run: |
        pytest